package BankApplication;

import java.util.ArrayList;
import java.util.List;

public abstract class BankAccount {

	// Unique number generated by branch
	private String accountNumber;
	// Constraint on current balance
	private double minimumBalance;
	// Current Amount
	private double currentBalance;
	// Percent Interest
	private double interestRate;
	// List of all transactions.
	// Latest transaction is at the end of list.
	private List<Transaction> transactions;

	public Double withdraw(double amount) {
		return null;
	}

	public Double deposit(double amount) {
		return null;
	}

	public List<Transaction> getTransactionHistory() {
		return transactions;
	}

	public List<Transaction> getMiniStatement() {
		List<Transaction> lastTenTransactions = null;
		if (transactions.size() >= 10) {
			lastTenTransactions = new ArrayList<Transaction>(
					transactions.subList(transactions.size() - 10, transactions.size() - 1));
		} else {
			lastTenTransactions = new ArrayList<Transaction>(transactions);
		}
		return lastTenTransactions;
	}

	public Double getMinimumBalance() {
		return minimumBalance;
	}

	public Double getCurrentBalance() {
		return currentBalance;
	}

	public Double getInterestRate() {
		return interestRate;
	}

	abstract String getType();

}
